### PR TITLE
Messages index and new pages added.

### PR DESCRIPTION
**Pull request by Alpkant**
Personal message show page and sending new message pages added.

### CODE REVIEW

**Comment by Alpkant** [comment]
Guys i added the page that we will show personal messages and page that user can send new message to restaurant users. I am not sure about the design , feel free to change the design.

**Review by Bekci — APPROVED** [review]
Looks fine. Thank you!

**Review by sadikekin — APPROVED** [review]
This message pages are so good, that makes me want to communicate with people. Good job @Alpkant

**Review by onatsahin — APPROVED** [review]
Sorry for the late review

**Pull request merged**
