### PR TITLE
manifest.yml changes for bluemix host

### PR DESCRIPTION
**Pull request by sadikekin**

### CODE REVIEW

**Comment by sadikekin** [comment]
So, guys,  i changed name variable to our name(itucsdb1708). This is mandatory for Bluemix deploy. I got error because of this

**Comment by sadikekin** [comment]
screen shot 2017-09-27 at 10 07 19 pm

**Comment by Alpkant** [comment]
Okay seems good.

**Comment by Bekci** [comment]
Thanks, we grateful.

**Comment by onatsahin** [comment]
Good job Ekin.

**Comment by sadikekin** [comment]
We changed our repository. Furthermore, we created a new organization.We think it is okay now.

**Pull request merged**
