### PR TITLE
Restaurants

### PR DESCRIPTION
**Pull request by sadikekin**

### CODE REVIEW

**Review by Alpkant — APPROVED** [review]
Thanks Ekin, this fix is on fire !

**Review by onatsahin — APPROVED** [review]

**Review by Bekci — APPROVED** [review]
Nice work!

**Comment by sadikekin** [comment]
Guys i have not done with this branch. Why you guys approved me?

**Review by Alpkant — COMMENTED** [review]
If you didn't finish changes why would you send pull request ?

**Comment by sadikekin** [comment]
Thanks for reply @Alpkant. All of my changes will be protected if my computer breaks or something.

**Comment by Alpkant** [comment]
@sadikekin you can still push your branch to the GitHub it will still be available but pull requests meant to be pushed to the master.

**Comment by sadikekin** [comment]
Well @Alpkant, It is not my fault for approving the pull request without reading the files.

**Pull request merged**
