### PR TITLE
Tables and classes for deals and orders

### PR DESCRIPTION
**Pull request by onatsahin**
Please check it out guys

### CODE REVIEW

**Review by Bekci — APPROVED** [review]
That’s really nice!

**Review by Alpkant — APPROVED** [review]
Our first pyhon class. So exiting.

**Comment by onatsahin** [comment]
Guys I changed the name of Order table to Orders I think it is safer now
3087687-7217280674-goku_

**Review by sadikekin — APPROVED** [review]
it is ok

**Pull request merged**
