### PR TITLE
Queries

### PR DESCRIPTION
**Pull request by Bekci**
I write queries of my tables to handlers.py also fixed other tables. Please check it.

### CODE REVIEW

**Review by Alpkant — APPROVED** [review]
Wow lots of bug fixes, great!

**Comment by sadikekin** [comment]
call-911-because-you-are-on-fire
;)

**Review by sadikekin — APPROVED** [review]

**Review by onatsahin — APPROVED** [review]
kakashi_thumbs_up

**Comment by ynsgnr** [comment]
BEST TEAM ON THE GITHUB SO JELLY

**Pull request merged**
