### PR TITLE
developer doc is added

### PR DESCRIPTION
**Pull request by sadikekin**

### CODE REVIEW

**Review by Alpkant — APPROVED** [review]
Thank you for this awesome documentation.

**Review by Bekci — APPROVED** [review]
Looks cool!

**Comment by sadikekin** [comment]
@Bekci  I think there is a conflict on your part. Can you solve the conflict?

**Comment by Bekci** [comment]
I solved them. It is ready to merge!

**Review by onatsahin — APPROVED** [review]

**Pull request merged**
