### PR TITLE
User and Message Databases created.

### PR DESCRIPTION
**Pull request by Alpkant**
I have created SQL files of User and Message databases

### CODE REVIEW

**Comment by sadikekin** [comment]
Why did you use .sql file @Alpkant

**Comment by Alpkant** [comment]
Sorry @sadikekin  i confused about .sql and .sqlite . I am correcting it right away. Thanks.

**Review by Bekci — APPROVED** [review]
Great job. Thank you!

**Review by onatsahin — APPROVED** [review]
Cool

**Pull request merged**
